### PR TITLE
Add CS Degree to Sidebar

### PR DESCRIPTION
**Pull request by kayleebement**
can now add CS degree and see 1 requirement, also adding classes trigger the correct WAYS

- added warning field to requirements schema
- added CS major math requirement to requirements.json
- renamed requirement modal to degree modal
- added API for getting school given school id
- modified how requirements are stored in App.js

however:
I do get this error when adding a class, didn't have time to figure it out
image

### CODE REVIEW

**Comment by garrickf** [comment]
The error should be ok? I redid the addClass and put in into Redux in my branch, and I think the error isn't there.

**Comment by kayleebement** [comment]
ok does that mean you approve ?

**Comment by kate-rydberg** [comment]
does this fix not being able to add majors / minors to sidebar?

**Comment by garrickf** [comment]
> ok does that mean you approve ?

Sorry I haven't really taken a full look at the code but I should be able to tonight! Post 8pm

**Pull request merged**
