### PR TITLE
Tracks

### PR DESCRIPTION
**Pull request by kayleebement**
now you can select track from the degree modal (when applicable) and the requirement card will only show the requirements corresponding to that track!

### CODE REVIEW

**Comment by garrickf** [comment]
There seems to be a merge conflict and a bug: when you select a major without tracks (aero/astro, for example), then you get Cannot convert undefined or null to object. I'm looking into this now!

**Comment by kayleebement** [comment]
Are you sure it's all majors without tracks or just majors that don't have requirements in the database? I tested ones without tracks but might have forgotten the other case

**Comment by kayleebement** [comment]
Also lmk if you want me to look into the bug / resolve the conflicts (forgot master was updated oops!)

**Comment by garrickf** [comment]
Oh hm I believe Aero/Astro had requirements in the DB but it didn't work for me; perhaps my database is out of date or something? I think I might head to lathrop soon so we can double check that bug; but yeah you can take the merge conflict!

**Comment by kayleebement** [comment]
ok either way it's probably good to add that extra check :)

**Comment by kayleebement** [comment]
fixed merge conflicts and tested, seems to be working, lmk if you find anything else tho!

**Pull request merged**
